INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  6 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table',  5 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  5 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Refrigerator',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  9 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Refrigerator',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  2 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table',  8 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table',  4 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  5 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table',  1 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Microscope',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  8 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'incubator',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  2 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Microscope',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  5 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Microscope',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Feeding Pump',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  5 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  4 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  8 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Incubator',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  5 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Incubator',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  2 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Feeding Pump',  5 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'incubator',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Microscope',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  8 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Incubator',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  6 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Lab Refrigerator',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'incubator',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table',  6 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  6 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  1 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  7 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Incubator',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Monitor',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'incubator',  5 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  4 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  1 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  8 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  4 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  5 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'incubator',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'IV Pole',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Chair',  5 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  7 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  3 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Warmer',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  1 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Table lamp',  7 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infant Incubator',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Infusion Pump',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Fetal Doppler',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  6 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Bed',  3 );
INSERT INTO Nonmedical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Nebulizer',  9 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
INSERT INTO Equipment(Name, Quantity) VALUES ( 'Laryngoscope',  8 );
INSERT INTO Medical_equipment(Equipment_id) VALUES ( (SELECT CURRVAL('Equipment_equipment_id_seq') ) );
