INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('michaelbeck','_#sE8lynT4' , 3 , '2013-02-14 14:00:24' , '2019-11-19 21:01:32');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (13307172 , (SELECT CURRVAL('account_account_id_seq') ),'Lauren Hunt' , 'Nurse' );
INSERT INTO Medical_staff(Passport_number) VALUES (13307172);
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('james90','cSX4H%Nh$5' , 4 , '2012-04-10 13:10:38' , '2019-11-20 04:13:17');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (68872670 , (SELECT CURRVAL('account_account_id_seq') ),'Robert Johnson' , 'IT department' );
INSERT INTO Nonmedical_staff(Passport_number) VALUES (68872670);
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('ericcardenas','b&zh#7Hh&s' , 1 , '2010-09-17 12:13:58' , '2019-11-24 02:44:16');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (92104891 , (SELECT CURRVAL('account_account_id_seq') ),'Melissa Oconnell' , 'Doctor' );
INSERT INTO Medical_staff(Passport_number) VALUES (92104891);
INSERT INTO Doctor(MS_id, Specialization) VALUES ((SELECT CURRVAL('medical_staff_ms_id_seq')), 'Cardiology' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '21:00' );
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('mayosandra','%#W4nLDfT2' , 1 , '2011-11-16 03:05:53' , '2019-11-21 01:52:53');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (24510592 , (SELECT CURRVAL('account_account_id_seq') ),'Tara Ellis' , 'Doctor' );
INSERT INTO Medical_staff(Passport_number) VALUES (24510592);
INSERT INTO Doctor(MS_id, Specialization) VALUES ((SELECT CURRVAL('medical_staff_ms_id_seq')), 'Obstetrics & Gynecology' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '23:00' );
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('kathyjohnson','&7N2!Wy+Qb' , 2 , '2012-10-14 17:03:43' , '2019-11-21 04:05:18');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (94034967 , (SELECT CURRVAL('account_account_id_seq') ),'Stacey Brown' , 'Doctor' );
INSERT INTO Medical_staff(Passport_number) VALUES (94034967);
INSERT INTO Doctor(MS_id, Specialization) VALUES ((SELECT CURRVAL('medical_staff_ms_id_seq')), 'Bariatric Medicine/Surgery' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '23:00' );
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('franciscosimmons','+GSv#9jY66' , 1 , '2019-09-14 22:55:17' , '2019-11-18 16:42:29');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (65079553 , (SELECT CURRVAL('account_account_id_seq') ),'Brian Perkins' , 'Doctor' );
INSERT INTO Medical_staff(Passport_number) VALUES (65079553);
INSERT INTO Doctor(MS_id, Specialization) VALUES ((SELECT CURRVAL('medical_staff_ms_id_seq')), 'Cardiology' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '15:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '16:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '18:00' );
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('lmorgan','7fi7Zo)8Z)' , 4 , '2017-08-29 05:53:23' , '2019-11-23 02:37:46');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (54565050 , (SELECT CURRVAL('account_account_id_seq') ),'Joseph Greene' , 'Adminstration' );
INSERT INTO Nonmedical_staff(Passport_number) VALUES (54565050);
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('ogray',')EA@z2Bk1w' , 1 , '2014-06-17 02:57:13' , '2019-11-24 09:41:52');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (32282948 , (SELECT CURRVAL('account_account_id_seq') ),'Daniel Hill' , 'Doctor' );
INSERT INTO Medical_staff(Passport_number) VALUES (32282948);
INSERT INTO Doctor(MS_id, Specialization) VALUES ((SELECT CURRVAL('medical_staff_ms_id_seq')), 'Colorectal Surgery' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SUN' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '4:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '7:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'MON' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '1:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '2:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '21:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '22:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'TUE' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '0:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '6:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '18:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'WED' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '12:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'THU' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '5:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '10:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '11:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '13:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '17:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'FRI' , '23:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '3:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '8:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '9:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '14:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '19:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '20:00' );
INSERT INTO Schedule(Doctor_id, Day, Time) VALUES ((SELECT CURRVAL('Doctor_doctor_id_seq')), 'SAT' , '21:00' );
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('james99','V71NNQVu*V' , 3 , '2015-02-07 01:10:34' , '2019-11-23 10:34:05');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (52225888 , (SELECT CURRVAL('account_account_id_seq') ),'Michael Stokes' , 'Nurse' );
INSERT INTO Medical_staff(Passport_number) VALUES (52225888);
INSERT INTO Account(Login, Password, Permission_level, Date_of_creation, Last_time_online) VALUES ('collinsanthony','x!4bZNMy#P' , 3 , '2013-11-09 05:08:38' , '2019-11-21 11:16:06');
INSERT INTO Staff(Passport_number, Account_id, Full_name, Position) VALUES (57835174 , (SELECT CURRVAL('account_account_id_seq') ),'Ryan Cruz' , 'Nurse' );
INSERT INTO Medical_staff(Passport_number) VALUES (57835174);
