# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Desktop\test\design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 497)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QWidget#centralwidget\n"
"{\n"
"    background-image: url(mujiki.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.buttons = QtWidgets.QWidget(self.centralwidget)
        self.buttons.setStyleSheet("QWidget#buttons\n"
"{\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"}")
        self.buttons.setObjectName("buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.query1_button = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query1_button.sizePolicy().hasHeightForWidth())
        self.query1_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.query1_button.setFont(font)
        self.query1_button.setObjectName("query1_button")
        self.verticalLayout.addWidget(self.query1_button)
        self.query2_button = QtWidgets.QPushButton(self.buttons)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.query2_button.setFont(font)
        self.query2_button.setObjectName("query2_button")
        self.verticalLayout.addWidget(self.query2_button)
        self.query3_button = QtWidgets.QPushButton(self.buttons)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.query3_button.setFont(font)
        self.query3_button.setObjectName("query3_button")
        self.verticalLayout.addWidget(self.query3_button)
        self.query4_button = QtWidgets.QPushButton(self.buttons)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.query4_button.setFont(font)
        self.query4_button.setObjectName("query4_button")
        self.verticalLayout.addWidget(self.query4_button)
        self.query5_button = QtWidgets.QPushButton(self.buttons)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.query5_button.setFont(font)
        self.query5_button.setObjectName("query5_button")
        self.verticalLayout.addWidget(self.query5_button)
        self.clear_button = QtWidgets.QPushButton(self.buttons)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear_button.setFont(font)
        self.clear_button.setAcceptDrops(False)
        self.clear_button.setAutoFillBackground(True)
        self.clear_button.setStyleSheet("")
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout.addWidget(self.clear_button)
        self.horizontalLayout.addWidget(self.buttons)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Luiz is handsome"))
        self.query1_button.setText(_translate("MainWindow", "I am a bag forgetter"))
        self.query2_button.setText(_translate("MainWindow", "Show appointments statistics"))
        self.query3_button.setText(_translate("MainWindow", "Show patients who should receive home visits"))
        self.query4_button.setText(_translate("MainWindow", "Show monthly income"))
        self.query5_button.setText(_translate("MainWindow", "Show the best doctors"))
        self.clear_button.setText(_translate("MainWindow", "Clear output"))

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.host_tb = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.host_tb.sizePolicy().hasHeightForWidth())
        self.host_tb.setSizePolicy(sizePolicy)
        self.host_tb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.host_tb.setObjectName("host_tb")
        self.gridLayout.addWidget(self.host_tb, 0, 1, 1, 1)
        self.db_name_tb = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_name_tb.sizePolicy().hasHeightForWidth())
        self.db_name_tb.setSizePolicy(sizePolicy)
        self.db_name_tb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.db_name_tb.setObjectName("db_name_tb")
        self.gridLayout.addWidget(self.db_name_tb, 1, 1, 1, 1)
        self.password_tb = QtWidgets.QPlainTextEdit(Dialog)
        self.password_tb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.password_tb.setObjectName("password_tb")
        self.gridLayout.addWidget(self.password_tb, 3, 1, 1, 1)
        self.login_tb = QtWidgets.QPlainTextEdit(Dialog)
        self.login_tb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.login_tb.setObjectName("login_tb")
        self.gridLayout.addWidget(self.login_tb, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        #QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connect to database"))
        self.label.setText(_translate("Dialog", "Host name"))
        self.label_2.setText(_translate("Dialog", "Database name"))
        self.label_3.setText(_translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "Password"))

    #import bckgrnd_rc
